### PR TITLE
Add docs to the single version image

### PR DESCRIPTION
**Pull request by bkabrda**

### CODE REVIEW

**Comment by rpitonak** [comment]
Is this branch still relevant? We stop updating it while ago and in my opinion we can delete it now and keep only master branch.

**Comment by bkabrda** [comment]
I have to say as a newcomer I have no idea. Perhaps @TomasTomecek knows?

**Comment by TomasTomecek** [comment]
I believe that after recent changes we kind of made this branch irrelevant and forgot to drop it and update docs.

**Comment by bkabrda** [comment]
Ok, thanks for the clarification. I'm closing this PR then.

**Comment by TomasTomecek** [comment]
Sorry it's not up to date and this was a waste of time.

**Pull request closed without merging**
